//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultImages
    {
        public System.Guid Id { get; set; }
        public System.Guid ConsultID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.Guid ClinicMenID { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string BlobURL { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid ClinicID { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual ClinicMen ClinicMen { get; set; }
        public virtual Consult Consult { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
