//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consult()
        {
            this.Remission = new HashSet<Remission>();
            this.ConsultImages = new HashSet<ConsultImages>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AppointmentID { get; set; }
        public System.DateTime ConsultStartTime { get; set; }
        public Nullable<System.DateTime> ConsultEndTime { get; set; }
        public string Notes { get; set; }
        public decimal Amount { get; set; }
        public int Number { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remission> Remission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultImages> ConsultImages { get; set; }
    }
}
