//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomFields()
        {
            this.CustomFieldValues = new HashSet<CustomFieldValues>();
        }
    
        public System.Guid Id { get; set; }
        public int FieldType { get; set; }
        public int EntityType { get; set; }
        public bool AllowAllEntities { get; set; }
        public string FieldText { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.Guid ClinicID { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomFieldValues> CustomFieldValues { get; set; }
    }
}
