//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public string InnerMessaje { get; set; }
        public string EntityInnerMessage { get; set; }
        public bool IsException { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.Guid> ClinicID { get; set; }
    }
}
