//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Appointment = new HashSet<Appointment>();
            this.ConsultImages = new HashSet<ConsultImages>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public System.Guid ClinicID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Birthdate { get; set; }
        public Nullable<System.DateTime> Deathdate { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string Address { get; set; }
        public byte[] Photo { get; set; }
        public int PatientNumber { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int Number { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Clinic Clinic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsultImages> ConsultImages { get; set; }
    }
}
