//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemissionPayment
    {
        public System.Guid Id { get; set; }
        public System.Guid RemissionID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Comments { get; set; }
        public System.Guid ClinicID { get; set; }
        public decimal PaymentAmount { get; set; }
        public decimal ExchangeRate { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Remission Remission { get; set; }
    }
}
