//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remission()
        {
            this.RemissionPayment = new HashSet<RemissionPayment>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ConsultID { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal VAT { get; set; }
        public System.Guid PatientID { get; set; }
        public string Notes { get; set; }
        public int Number { get; set; }
        public System.Guid ClinicMenID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Status { get; set; }
        public decimal Payed { get; set; }
        public System.Guid ClinicID { get; set; }
        public decimal ExchangeRate { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual Consult Consult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemissionPayment> RemissionPayment { get; set; }
    }
}
