//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.WebProject.Backend.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesRestore : DbContext
    {
        public EntitiesRestore()
            : base("name=EntitiesRestore")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AuxiliarPersonal> AuxiliarPersonal { get; set; }
        public virtual DbSet<Clinic> Clinic { get; set; }
        public virtual DbSet<ClinicMen> ClinicMen { get; set; }
        public virtual DbSet<Consult> Consult { get; set; }
        public virtual DbSet<ConsultImages> ConsultImages { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Remission> Remission { get; set; }
        public virtual DbSet<RemissionPayment> RemissionPayment { get; set; }
        public virtual DbSet<SucessfullLogins> SucessfullLogins { get; set; }
        public virtual DbSet<Supplies> Supplies { get; set; }
    }
}
