//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.AdminV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.Consult = new HashSet<Consult>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CreatedClinicMen { get; set; }
        public Nullable<System.Guid> CreatedAuxiliar { get; set; }
        public System.Guid ClinicMenID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Address { get; set; }
        public string Comments { get; set; }
        public int Type { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int Status { get; set; }
        public int Number { get; set; }
        public System.Guid ClinicID { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual ClinicMen ClinicMen { get; set; }
        public virtual ClinicMen ClinicMen1 { get; set; }
        public virtual AuxiliarPersonal AuxiliarPersonal { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consult> Consult { get; set; }
    }
}
