//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.AdminV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuxiliarPersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuxiliarPersonal()
        {
            this.Appointment = new HashSet<Appointment>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ClinicID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime HireDate { get; set; }
        public byte[] Photo { get; set; }
        public string Address { get; set; }
        public int Number { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Clinic Clinic { get; set; }
    }
}
