//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.AdminV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remission
    {
        public System.Guid Id { get; set; }
        public System.Guid ConsultID { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal VAT { get; set; }
        public System.Guid PatientID { get; set; }
        public string Notes { get; set; }
        public int Number { get; set; }
        public System.Guid ClinicMenID { get; set; }
    
        public virtual Consult Consult { get; set; }
    }
}
