//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.AdminV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucessfullLogins
    {
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public string IP { get; set; }
        public string UserId { get; set; }
        public System.Guid ClinicID { get; set; }
        public int ClinicNumber { get; set; }
    }
}
