//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sihapp.AdminV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        public System.Guid Id { get; set; }
        public long Number { get; set; }
        public string InternalCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public bool PrivateUse { get; set; }
        public System.Guid ClinicMenID { get; set; }
        public decimal CurrentStock { get; set; }
        public decimal VatAmount { get; set; }
        public decimal IEPSAmount { get; set; }
        public System.Guid ClinicID { get; set; }
    
        public virtual Clinic Clinic { get; set; }
        public virtual ClinicMen ClinicMen { get; set; }
    }
}
